name: Feature Branch PR Checks

on:
  pull_request:
    branches:
      - development
    paths-ignore:
      - "**/README.md"
    types: [opened, synchronize, reopened]

jobs:
  feature-pr-checks:
    runs-on: macos-latest
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: "5.8"
